from __future__ import annotations
from typing import Protocol
from dalg.model import Frame, Result


class Algorithm(Protocol):
    name: str
    sensors: tuple[str, ...]
    def start(self) -> None: ...
    def observe(self, frame: Frame) -> None: ...
    def preview(self) -> Result | None: ...
    def finish(self) -> Result: ...
